apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - image: klemen1999/auth-service:2023-01-07-20-12-51
          name: auth-service
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgres://snuffleupagus.db.elephantsql.com:5432/kbesujbr
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: kbesujbr
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass3
                  key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8084
              name: server
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 8084
      protocol: TCP
      targetPort: server
  selector:
    app: auth-service
